version: "3"

services:
    app:
        container_name: bot_app
        build:
            context: ../
            target: runtime
        restart: "always"
        env_file: ../.env
        volumes:
            - ../app:/code/app
            - /code/.venv
            - ../${PERSISTENCE}:/code/${PERSISTENCE}
